name: Bug Report
description: Report a bug to help us improve # STARTBTC
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar este bug.
  - type: textarea
    id: bug-description
    attributes:
      label: Descripción del Bug
      description: Una descripción clara y concisa de lo que está pasando.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Pasos para Reproducir
      description: Cuéntanos cómo podemos ver el error por nuestra cuenta.
      placeholder: |
        1. Ir a '...'
        2. Hacer click en '....'
        3. Ver el error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamiento Esperado
      description: Una descripción clara de lo que esperabas que pasara.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: OS, Node version, Browser, etc.
